version: '3'

services:
  ghostface:
    image: burningstack/ghostface:latest
    # Use this if you want to build the image yourself
    # build: .
    container_name: ghostface
    ports:
      - '5250:80'
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped

